language: node_js
notifications:
  email: false
node_js:
  - 10
  - 8
  - 6
script:
  - yarn lint
  - yarn test
  - yarn build
after_success: yarn coveralls
deploy:
  skip_cleanup: true
  provider: npm
  email: asharvit@redhat.com
  api_key: $NPM_TOKEN
  on:
    node: 10
    tags: true
    repo: sharvit/foreman-js

